# Site settings
title: Gabriel Balbuena
description: Tech notes and resources

url: 'http://gbalbuena.github.io'

# baseurl: ''

author:
  name: 'Gabriel'
  email: gabrielbalbuena@gmail.com
  linkedin_username: gabrielbalbuena
  github_username: gbalbuena
  # npm_username:
  # twitter_username:
  # facebook_username:
  # spotify:
  # instagram:
  # stackshare:

#features:
  # google_analytics: 'UA-93047835-1'
  # disqus_shortname:

# More information: https://jekyllrb.com/docs/collections/
collections:
  pages:
    output: true
    permalink: /:categories/:name

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
