# Site settings
title: My Untitled Blog
description: 'The grumpy developer'
url: 'http://gbalbuena.github.io'
baseurl: ''
google_analytics: 'UA-93047835-1'
disqus_shortname: 'gbalbuena'

author:
  name: 'Juan Gabriel Balbuena Balbuena'
  email: gabrielbalbuena@gmail.com
  # twitter_username: gabrielbalbuena
  # facebook_username: gabrielbalbuena
  # github_username:  gbalbuena
  linkedin_username:  gabrielbalbuena
  spotify: 12164436337
  instagram: gabbzbal

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
